Add back url dependency that was removed from hyper
panoptix-za/influxdb-rs pull request #2
Opened 2017-03-30 23:15 UTC by mre

The hyper crate goes through some big refactoring lately. `Url` was removed in favor of `Uri`. See the commits [here](https://github.com/hyperium/hyper/issues/1089#issuecomment-286252505) and [here](https://github.com/hyperium/hyper/pull/1100). This means, handling Urls needs to be adjusted. This also includes error handling (`ParseError` becomes `UriError`). I've went ahead and  added the url dependency back to make this crate compile again.

Fair warning: the unit tests don't pass, but that is probably because of the missing InfluxDB for the integration tests. I tested against a live InfluxDB and it works as expected.

```
running 10 tests
test query_nonexistent_db ... ignored
test multiple_queries_to_nonexistent_database ... FAILED
thread panicked while panicking. aborting.
error: process didn't exit successfully: `/.../influxdb-rs/target/debug/deps/basic-dc19e4820d9bb192` (signal: 4,
SIGILL: illegal instruction)
```

The conversion from url::Url to hyper::Uri is a bit cumbersome. I did not find any other way than converting to string and back. Also, I've added a nasty unwrap. This could be handled more gracefully by having a Result as a return type for the queries, but I would say it's fine for now since hyper used this same process internally until url was removed.

2017-03-31 13:17 UTC, shepmaster commented
> Fair warning: the unit tests don't pass, but that is probably because of the missing InfluxDB for the integration tests.

The [README describes what you need to do to allow running the tests](https://github.com/panoptix-za/influxdb-rs#running-the-tests).

@stephanbuys I'd recommend enabling the Travis-CI support to allow PRs to be automatically tested.

2017-03-31 13:45 UTC, shepmaster requested changes

2017-03-31 13:45 UTC, shepmaster commented on Cargo.toml
> +license = "MIT/Apache-2.0"
I don't see any reason for these lines to be modified.

2017-03-31 13:45 UTC, shepmaster commented on Cargo.toml
> +path = "influxdb-derive"
Ditto, these don't need to be modified.

2017-03-31 13:45 UTC, shepmaster commented on src/lib.rs
> +            hyper::Method::Post, hyper::Uri::from_str(self.write_endpoint.as_str()).unwrap());
It's unusual to use `from_str` directly; why did you choose that instead of the idiomatic `self.write_endpoint.as_str().parse()`?

2017-03-31 13:45 UTC, shepmaster commented on src/lib.rs
> +            self.client.get(hyper::Uri::from_str(query_endpoint.as_str()).unwrap())
I'd go ahead and change both `unwrap`s to `expect`s with a somewhat understandable error message.

2017-03-31 13:57 UTC, mre commented on Cargo.toml
> +license = "MIT/Apache-2.0"
This is the proposed structure when using `cargo add`, so I assumed it was the recommended structure. I can undo this change if you like.

2017-03-31 13:58 UTC, mre commented on Cargo.toml
> +path = "influxdb-derive"
ok

2017-03-31 14:01 UTC, shepmaster commented on Cargo.toml
> +license = "MIT/Apache-2.0"
`cargo add` doesn't preserve the incoming format of the TOML file. It's also "just" a third-party command, not one from the Rust project itself, so it doesn't have to represent a grand unified representation of TOML 😸.

I also use `cargo add`; my main quibble is with changing aspects unrelated to the same commit and/or PR. Things like that generally make digging through the git log much more difficult in the future.

2017-03-31 14:11 UTC, mre commented on Cargo.toml
> +license = "MIT/Apache-2.0"
Okay makes sense. Reverted.

2017-03-31 14:21 UTC, mre commented
Updated the PR to reflect the suggested changes. As for the tests, I set up a Docker environment now, that I could contribute to the project in a separate PR. Would you be interested in that?

I still get errors, though but I can see the requests coming in at the InfluxDB side.

```rust
running 10 tests
test query_nonexistent_db ... ignored
test add_data_asynchronously_udp ... FAILED
test multiple_queries_to_nonexistent_database ... FAILED
test test_infrastructure ... FAILED
test add_data_asynchronously ... FAILED
test batched_typed_insert ... FAILED
test query_asynchronously ... FAILED
test add_batched_data_asynchronously ... FAILED
test multiple_queries ... FAILED
test typed_insert ... FAILED

failures:

---- add_data_asynchronously_udp stdout ----
	thread 'add_data_asynchronously_udp' panicked at 'Unable to create UDP database: AddrParse(AddrParseError(()))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- multiple_queries_to_nonexistent_database stdout ----
	thread 'multiple_queries_to_nonexistent_database' panicked at 'Unable to run future to completion: Serde(Syntax(Message("missing field `statement_id`"), 1, 36))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- test_infrastructure stdout ----
	thread 'test_infrastructure' panicked at 'called `Result::unwrap()` on an `Err` value: Serialize(Syntax(Message("missing field `statement_id`"), 1, 136))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- add_data_asynchronously stdout ----
	thread 'add_data_asynchronously' panicked at 'called `Result::unwrap()` on an `Err` value: Serialize(Syntax(Message("missing field `statement_id`"), 1, 136))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- batched_typed_insert stdout ----
	thread 'batched_typed_insert' panicked at 'called `Result::unwrap()` on an `Err` value: Serialize(Syntax(Message("missing field `statement_id`"), 1, 248))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- query_asynchronously stdout ----
	thread 'query_asynchronously' panicked at 'Unable to run future to completion: Serde(Syntax(Message("missing field `statement_id`"), 1, 136))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- add_batched_data_asynchronously stdout ----
	thread 'add_batched_data_asynchronously' panicked at 'called `Result::unwrap()` on an `Err` value: Serialize(Syntax(Message("missing field `statement_id`"), 1, 228))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- multiple_queries stdout ----
	thread 'multiple_queries' panicked at 'Unable to run future to completion: Serde(Syntax(Message("missing field `statement_id`"), 1, 236))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

---- typed_insert stdout ----
	thread 'typed_insert' panicked at 'called `Result::unwrap()` on an `Err` value: Serialize(Syntax(Message("missing field `statement_id`"), 1, 146))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837


failures:
    add_batched_data_asynchronously
    add_data_asynchronously
    add_data_asynchronously_udp
    batched_typed_insert
    multiple_queries
    multiple_queries_to_nonexistent_database
    query_asynchronously
    test_infrastructure
    typed_insert

test result: FAILED. 0 passed; 9 failed; 1 ignored; 0 measured

error: test failed
```

`AddrParseError(())` doesn't look to good to me. I could step through with a debugger, but maybe you already see what could be the error here.

2017-03-31 14:29 UTC, mre commented on src/lib.rs
> +            hyper::Method::Post, hyper::Uri::from_str(self.write_endpoint.as_str()).unwrap());
Cool! Did not know about that. Thanks!

2017-04-01 00:06 UTC, shepmaster commented
> I set up a Docker environment now, that I could contribute to the project in a separate PR. Would you be interested in that?

I *personally* don't really have the need for it, but overall it seems useful. I'd leave that up to @stephanbuys to decide.

> missing field `statement_id`

On a quick search, it looks like this was a field added in Influx 1.2. Perhaps you've installed an older version? If @stephanbuys wants to support these previous versions, that might need to be made optional.

> AddrParse(AddrParseError(()))

No clue off the top of my head, but it's only for the UDP tests, so that's where I'd start looking.

2017-04-02 05:42 UTC, stephanbuys commented
@mre Do you need support for older version of InfluxDB? I don't mind merging this if the impact is low, we're only really getting started with InfluxDB now so we don't really need backwards compatibility.

2017-04-03 13:18 UTC, mre commented
@stephanbuys nope, that's fine. Don't need support for older versions. ;-)

2017-10-24 17:57 UTC, shepmaster commented
@stephanbuys any objections to merging this?

2017-10-24 17:57 UTC, shepmaster approved these changes

2017-10-24 17:57 UTC, mre commented
@shepmaster thanks for supporting me here :-)

2017-10-24 18:09 UTC, stephanbuys commented
Happy to!

2017-10-24 18:09 UTC, merged