Await completion of future in example
panoptix-za/influxdb-rs pull request #3
Opened 2017-03-30 23:23 UTC by mre

For a first time user, it's nice to have a "happy moment" when using a new library for the first time. While running the example code from the `README`, I was a bit confused why I couldn't see my data in InfluxDB. Of course the solution was to simply wait for the future to complete.
Do you think it makes sense to add this final line to the example to write the data to InfluxDB when the code is executed?

2017-03-31 13:12 UTC, shepmaster commented
> was to simply wait for the future to complete.

That's actually not guaranteed to show the data in Influx. Influx only acknowledges that it has *received* your request, not that it's *indexed* it. When it's under heavy load, this becomes more obvious.

2017-03-31 13:13 UTC, shepmaster requested changes

2017-03-31 13:13 UTC, shepmaster commented on README.md
> +    core.run(insert).expect("Unable to run future to completion");
This example is also present in `lib.rs`; would you please make the same change there?

2017-03-31 13:21 UTC, mre commented on README.md
> +    core.run(insert).expect("Unable to run future to completion");
Sure. Done. 👍

2017-03-31 13:57 UTC, shepmaster approved these changes

2017-03-31 13:58 UTC, shepmaster commented
The content of the changes looks OK to me. Were this my repository, I'd want the two commits squashed, but I'll leave such decisions up to @stephanbuys , as well as the merge itself.

2017-03-31 14:14 UTC, mre commented
Can't commits be squashed on merge with Github? Just curious.

2017-03-31 23:59 UTC, shepmaster commented
> Can't commits be squashed on merge with Github?

That's certainly something that the GH UI allows; I've never done it myself.

2017-04-02 05:34 UTC, stephanbuys commented
Trying "squash and merge" from GH GUI... Apologies I'm out of town for a small while, so may not be very responsive.

2017-04-02 05:34 UTC, merged